### ISSUE TITLE
delete blockquotes from the blog template

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/empress-blog-ember-template#109]
**Note, this issue is reserved for EmberConf contributors workshop. Please volunteer for the issue if you are participating in the workshop.**

We already moved block quotes to ember-styleguide so we should delete references to block quotes from the blog template:

https://github.com/ember-learn/empress-blog-ember-template/blob/master/tests/dummy/content/the-editor.md#adding-quotes

https://github.com/ember-learn/empress-blog-ember-template/blob/master/addon/styles/blockquote.css

https://github.com/ember-learn/empress-blog-ember-template/blob/43acec07c29b408c19579c9487b1d6e31f88433f/addon/styles/addon.css#L1

**Comment by theklr** [comment]
tackling this
