### ISSUE TITLE
Implement PostCard component

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#25]
## Description

Implement the `<PostCard />` component, which is used to give a summary of a particular post on the index page and also the author page.

![PostCard](https://user-images.githubusercontent.com/594890/79160453-b534e180-7dd1-11ea-8e8a-05a0fbb41ac2.png)

Abstract link: https://app.abstract.com/share/a0507989-278d-4684-9c1c-c436eddbba2b?collectionLayerId=fb616254-a983-410a-b31b-254bee8a68c3&mode=build&selected=3275462493-E0A95F80-C807-445E-BE41-DCF99C21C86D

If you would like to work on this issue you can "claim" it by commenting and letting us know that you would like to work on it 👍 

## Supporting information - please read if you are new to this project

This redesign effort is powered by the new version of the Ember Styleguide. You should be able to implement everything you need for this feature by following the [new documentation for the ember-styleguide](https://ember-styleguide.netlify.app/) but if you think there is not enough documentation please let us know and we will point you in the right direction.

In most cases you should not need any CSS to implement this issue for the blog template, you should instead be trying to make use of the helpers and components that are documented in the ember-styleguide. This is not a strict rule, there may be cases where the documentation in the ember-styleguide is lacking or some custom CSS is actually needed. If you have any questions please comment on this issue or reach out to us on the `#st-website` channel on the [Ember Community Discord](https://discord.gg/emberjs)

**Comment by geekosupremo** [comment]
_Takes deep breath_
Ok, Let's do this. **I'd like to work on this.**

**Comment by mansona** [comment]
I was just chatting to @geekosupremo and he mentioned that he won't be able to take this one on 👍 

If anyone else wants to take it please feel free 🎉

**Comment by ankushdharkar** [comment]
I'll like to take this up please

**Comment by ankushdharkar** [comment]
I'd like to take this up please :)

**Comment by mansona** [comment]
Hey @ankushdharkar have you done anything on this issue yet? I'm just asking because I would prefer if you could focus on getting https://github.com/ember-learn/empress-blog-ember-template/pull/39 done before claiming another issue if that's ok? :)

I'm just asking because we have a few other contributors that are looking for tasks and it would be best if we have things to be able to assign 👍  is that ok?
