### ISSUE TITLE
Implement TagPostList component

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#26]
## Description

Implement the `<TagPostList />` component that takes a `@tag` as an argument and shows the title of that tag, a list of the latest 3 posts in that tag and a link to the tag page as the `More <tagname>...` link

![tag](https://user-images.githubusercontent.com/594890/79162285-eb279500-7dd4-11ea-9b0a-193f992f2619.png)

Abstract link: https://app.abstract.com/share/a0507989-278d-4684-9c1c-c436eddbba2b?collectionLayerId=fb616254-a983-410a-b31b-254bee8a68c3&mode=build&selected=3275462493-2CB5668F-A874-4797-A23D-83C28BF247AC

If you would like to work on this issue you can "claim" it by commenting and letting us know that you would like to work on it 👍 

## Supporting information - please read if you are new to this project

This redesign effort is powered by the new version of the Ember Styleguide. You should be able to implement everything you need for this feature by following the [new documentation for the ember-styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/) but if you think there is not enough documentation please let us know and we will point you in the right direction.

In most cases you should not need any CSS to implement this issue for the blog template, you should instead be trying to make use of the helpers and components that are documented in the ember-styleguide. This is not a strict rule, there may be cases where the documentation in the ember-styleguide is lacking or some custom CSS is actually needed. If you have any questions please comment on this issue or reach out to us on the `#st-website` channel on the [Ember Community Discord](https://discord.gg/emberjs)

**Comment by alexeykostevich** [comment]
@mansona , please, could I assign me to this ticket?

**Comment by mansona** [comment]
@alexeykostevich consider it done 🎉 

keep in contact with me on this one, the `Tag` model might not have everything that you need but that will be covered by a different task 🤔 if we keep the conversation up then it shouldn't be a problem 👍

**Comment by alexeykostevich** [comment]
Sounds great, @mansona ! Thank you for drawing my attention to this!

While I'm learning the codebase, please, let me ask a question about UI. According to the [wireframe](https://app.abstract.com/share/a0507989-278d-4684-9c1c-c436eddbba2b?collectionLayerId=fb616254-a983-410a-b31b-254bee8a68c3&mode=build&selected=3275462493-2CB5668F-A874-4797-A23D-83C28BF247AC) there are 2 patterns for showing tags:

## Inline Tags

<img width="246" alt="Screen Shot 2020-04-30 at 12 45 10 am" src="https://user-images.githubusercontent.com/5205189/80610041-3223b480-8a7c-11ea-89bc-2cf54593f0a4.png">

## Stacked Tags

<img width="257" alt="Screen Shot 2020-04-30 at 12 48 15 am" src="https://user-images.githubusercontent.com/5205189/80610141-567f9100-8a7c-11ea-8e77-0273475048b3.png">

It seems we need 2 separate components for them. Does this ticker cover only the latter or both?

**Comment by mansona** [comment]
This ticket should only address the latter case, because they use case is very different 👍 

The inline tags that you're showing will essentially just be links to the respective tag page (e.g. https://blog.emberjs.com/tag/2019) and the implementation will likely not need a component of its own and will be covered by https://github.com/ember-learn/empress-blog-ember-template/issues/31

Does that answer your question?

**Comment by alexeykostevich** [comment]
Yes, sounds good. Thank you!

**Comment by alexeykostevich** [comment]
Hello @mansona ,

I've implemented the draft version of the `<TagPostList />` component using [ember-styleguide].

The only style I had to add is to make a title gray:

```css
.tag-post-list .tag-post-list-title {
    color: var(--color-gray-600);
}
```

Here is how it looks like:

<img width="280" alt="Screen Shot 2020-05-01 at 1 25 18 am" src="https://user-images.githubusercontent.com/5205189/80728897-d411d280-8b4a-11ea-8234-497dfd80e13b.png">

Please, let me know if any changes are needed.

With regards to the model, as you mentioned above, the `Tag` model does not contain information about the latest 3 posts. 

I would recommend to render all the posts for now, add `TODO` and update one line when https://github.com/ember-learn/empress-blog-ember-template/issues/31 is ready.

```handlebars
<!-- 
TODO: Update the line below to use the top posts embedded into the model.
https://github.com/ember-learn/empress-blog-ember-template/issues/27
-->
{{#each @tag.posts as |post|}}
  <li class="my-1">
    <LinkTo @route="tag" @model={{post.id}}>
      {{post.title}}
    </LinkTo>
  </li>
{{/each}}
```

Please, let me know if you have any concerns.

**Comment by mansona** [comment]
ah yes, I see what you mean about it "not [having] information about latest 3 posts" but I don't know that we need to worry about that 🤔 I think we can just use the **first** 3 posts in the `@tag.posts` and then it means that we need to make sure that the first 3 are always the latest 3 🤔 

Are you able to try that for now and we can circle back when it's done to see if the first three actually matches our need for the latest?

**Comment by mansona** [comment]
Also as for the design, I'm looking at the abstract and it seems like it was intentional that the links don't have underlines in them 🤔 It might be something that we can abstract out into a CSS helper to be able to apply `class="no-link-underline"` but if you could just add it with the css that you're writing, for now, that would be super! (note: I think the underline is actually a background so if you do `background:none` it will fix it)

**Comment by alexeykostevich** [comment]
Thank you, @mansona , for your guidance!

We can definitely render just the first 3 posts in the `@tag.posts`. Unfortunately, `@tag.posts` are not currently sorted. Here is what we would get if we rendered the date:

<img width="442" alt="Screen Shot 2020-05-01 at 8 56 58 pm" src="https://user-images.githubusercontent.com/5205189/80800995-599a8e80-8bee-11ea-91a3-67b20b0283d9.png">

To keep components simple and performant, it would be great to handle this issue on the model level.

With regards to the underlines, thank you for drawing my attention to this and the great tip. I've `<TagPostList />` styles accordingly. If you would link me to add the `no-link-underline` helper to [ember-styleguide](https://github.com/ember-learn/ember-styleguide) at some point, please, let me know.

**Comment by mansona** [comment]
@alexeykostevich yes exactly, this is what I would prefer. You should ignore the ordering of `@tags.posts` for now and I'll make an issue to double-check this is correct before we release 👍 

I'll create an issue to add the helper now in ember-styleguide but it's not a priority (or a blocker) so we can just ignore it for now 👍

**Comment by alexeykostevich** [comment]
Sounds great! Thank you, @mansona! I’ll add tests and create PR tomorrow.
