### ISSUE TITLE
Implement Index page for desktop

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#30]
## Description

Implement the index page **for desktop view**

![blog @wide](https://user-images.githubusercontent.com/594890/79164400-e95fd080-7dd8-11ea-949f-22ab6a108bd7.png)

Abstract link: https://app.abstract.com/share/a0507989-278d-4684-9c1c-c436eddbba2b?collectionLayerId=fb616254-a983-410a-b31b-254bee8a68c3&mode=build&selected=root-79814B20-2D73-4442-9882-2450E5C85FF3

If you would like to work on this issue you can "claim" it by commenting and letting us know that you would like to work on it 👍 

Note: this issue only refers to the **desktop** view of the index page. The mobile view is blocked by #24 

Also blocked by #7 and https://github.com/ember-learn/empress-blog-ember-template/issues/31

## Supporting information - please read if you are new to this project

This redesign effort is powered by the new version of the Ember Styleguide. You should be able to implement everything you need for this feature by following the [new documentation for the ember-styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/) but if you think there is not enough documentation please let us know and we will point you in the right direction.

In most cases you should not need any CSS to implement this issue for the blog template, you should instead be trying to make use of the helpers and components that are documented in the ember-styleguide. This is not a strict rule, there may be cases where the documentation in the ember-styleguide is lacking or some custom CSS is actually needed. If you have any questions please comment on this issue or reach out to us on the `#st-website` channel on the [Ember Community Discord](https://discord.gg/emberjs)

**Comment by nickschot** [comment]
This issue probably requires no work anymore as most is implemented in separate issues (e.g. #52  #25 )

**Comment by mansona** [comment]
all of the related issues are now done 🎉
