### ISSUE TITLE
Implement TagSidebar component

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#31]
## Description

Implement the `<TagSidebar />` component. The tag sidebar consists of 3 `<TagPostList />` components (see #26) with 3 following sections 'By Year', 'By Major Version', and 'By subject'

The `By year` section is just a list of "year based" tag links. i.e. the `2019` link will just link to `/tag/2019`. The same is the case for the `By major version` section.

the `by subject` is also list of links to particular tags, essentially all other tags that don't have a dedicated section. Because tags can be created later, we won't make this a static list. Instead we will filter out tags that are already shown above this section from the `all tags` collection 👍 

![tagsidebar](https://user-images.githubusercontent.com/594890/79164774-a5210000-7dd9-11ea-8f08-ed00b4a33cd4.png)

Abstract link: https://app.abstract.com/share/a0507989-278d-4684-9c1c-c436eddbba2b?collectionLayerId=fb616254-a983-410a-b31b-254bee8a68c3&mode=build&selected=2417309410-C899CB5A-0D1F-488E-B994-7624B84ED51A

If you would like to work on this issue you can "claim" it by commenting and letting us know that you would like to work on it 👍 

## Supporting information - please read if you are new to this project

This redesign effort is powered by the new version of the Ember Styleguide. You should be able to implement everything you need for this feature by following the [new documentation for the ember-styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/) but if you think there is not enough documentation please let us know and we will point you in the right direction.

In most cases you should not need any CSS to implement this issue for the blog template, you should instead be trying to make use of the helpers and components that are documented in the ember-styleguide. This is not a strict rule, there may be cases where the documentation in the ember-styleguide is lacking or some custom CSS is actually needed. If you have any questions please comment on this issue or reach out to us on the `#st-website` channel on the [Ember Community Discord](https://discord.gg/emberjs)

**Comment by alexeykostevich** [comment]
Hi @mansona ,

I might be able to help with this work. Please, let me ask a few questions to understand a way forward better:

1. Is it correct to say that `TagSidebar` should find `Recent posts`, `Releases` and `The Ember Times` tags in the list of all tags and display a `TagPostList` for found ones?
2. Should the `By Year` and `By major version` tags be predefined (hard-coded) or found in a list of all tags (by the pattern)? If hard-coded, how will we maintain the relevancy of the value range due to the dynamic nature of time and releases?

Also, thinking about the implementation, I would recommend to consider a few changes:

1. Rename `TagSidebar` to `TagPanel` to keep it responsible only for managing tags and move sidebar responsibilities if any (e.g. layout, expand/collapse functionality for the mobile screens, accessibility) to a separate `BlogSidebar` or `TagSidebar` component. So, at the end we would have something like this:
```handlebars
<BlogSidebar>
  <TagPanel @tags={{@model.tags}} />
</BlogSidebar>
```
2. Implementing separate `TagRangeList` component for `By Year` and `By major version` tags for consistency with other parts and better testability.

I apologize if I'm missing something. Please, let me know if making a call to discuss this if it would be more convenient for you.

**Comment by mansona** [comment]
Great questions 😗 👌 

> Is it correct to say that TagSidebar should find Recent posts, Releases and The Ember Times tags in the list of all tags and display a TagPostList for found ones?

Yes 100% 👍  that's why that component used to be a blocker for this one

> Should the By Year and By major version tags be predefined (hard-coded) 

Yes. We should hard-code these links for now. What you're saying is correct that they are technically dynamic, but a once-a-year update (for the years) is not that big a deal for now. We can spend the time to improve this later 👍 

> Rename TagSidebar to TagPanel

Yes, yes, triple yes 🎉 this will work particularly well with the work that Nick is doing on the sidebar 👍 And your example looks great and exactly how I would expect it to work

> Implementing separate TagRangeList

No I think for now it makes sense to go with the hardcoding solution and we can come back to this optimisation if we need to 👍

**Comment by alexeykostevich** [comment]
Thank you for the detailed answers, @mansona ! This answers all my questions :)

I would like to start working on this, and hopefully, will be able to create a PR by Monday.

**Comment by mansona** [comment]
Well detailed questions get detailed answers 🤣🎉

Great thanks again for all the work you're doing 👍

**Comment by alexeykostevich** [comment]
@mansona , working on the component I found out that there are mismatches between some tag names and UI title.

According, to the wireframes, the component needs to show the following `TagPostList`s:
- Recent Posts
- Releases
- The Ember Times

However, tags, available in the application, do not always follow this naming:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/5205189/81576802-0db8c800-93ec-11ea-9fbc-db344f68c40b.png">

The inconsistency exists in the existing [Ember Blog](https://blog.emberjs.com/) as well:

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/5205189/81575875-e0b7e580-93ea-11ea-9cf3-08fa87d48fcf.png">

Would it possible to fix these inconsistencies on the data level? If yes, our tags could look like these:

```js
// Option 1: Update blog data to make `id` and `name` 
// match the corresponding titles on UI.
[
   { id: "recent-posts", name: "Recent Posts", ... }, 
   { id: "releases", name: "Releases", ...  },
   { id: "the-ember-times", name: "The Ember Times", ...  }
]

// Option 2: Update blog data to make `name` match 
// the corresponding titles on UI.
[
   { id: "new", name: "Recent Posts", ...  }, 
   { id: "releases", name: "Releases", ...  },
   { id: "newsletter", name: "The Ember Times", ...  }
]
```

If this is not feasible, we will need to update `TagPostList` to accept a custom title for a tag. However, this will add extra complexity to the component, which would be better to avoid.

Please, let me know what you think.

Thank you!

**Comment by alexeykostevich** [comment]
@mansona , this is a very draft version of the component class for an early feedback. Likely, it can be optimized (e.g. using `Map`) but please ignore performance concerns for now -- I'll have a look at this if the general approach looks correct.

```js
import Component from '@glimmer/component';

const recentPostsTagId = 'new';
const releasesTagId = 'releases';
const emberTimesTagId = 'newsletter';
const versionTagIds = ['version-3.x', 'version-2.x', 'version-1.x'];
const yearTagIds = ['2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012'];

export default class TagPanel extends Component {
  get recentPostsTag() {
    return this.args.tags.find(tag => tag.id === recentPostsTagId);
  }

  get releasesTag() {
    return this.args.tags.find(tag => tag.id === releasesTagId);
  }

  get newsletterTag() {
    return this.args.tags.find(tag => tag.id === theEmberTimesTagId);
  }

  get versionTags() {
    return versionTagIds
      .map(id => this.args.tags.find(tag => tag.id === id))
      .filter(Boolean);
  }

  get yearTags() {
    return yearTagIds
      .map(id => this.args.tags.find(tag => tag.id === id))
      .filter(Boolean);
  }

  get subjectTags() {
    const usedTagIds = [
      recentPostsTagId,
      releasesTagId,
      emberTimesTagId,
      ...versionTagIds,
      ...yearTagIds
    ];

    return this.args.tags.filter(tag => !usedTagIds.includes(tag.id));
  }
}
```

A tempting alternative might be using `RegExp` for finding `By Year` and `By major versions` tags by their pattern:

```js
...
const versionTagIds = ['version-3.x', 'version-2.x', 'version-1.x'];
const yearTagIds = ['2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012'];

export default class TagPanel extends Component {
  ...

  get versionTags() {
    return versionTagIds
      .map(id => this.args.tags.find(tag => tag.id === id))
      .filter(Boolean);
  }

  get yearTags() {
    return yearTagIds
      .map(id => this.args.tags.find(tag => tag.id === id))
      .filter(Boolean);
  }

 ...
}
```

However, it will likely cause issues with maintaining the correct order (descending) of these tags on UI, so I lean towards the first solution.

**Comment by mansona** [comment]
Again, great work that you're doing here 🎉  Although if you would like to work on a "draft implementation" please feel free to open a PR so that we can see it in action. There is no need to hold back until it's perfect to open a PR (the quality of your previous PR was vastly above what is generally expected from people anyway 😂)

> ignore performance concerns for now

I would say ignore any performance concerns forever 👍 there is no need to hyper optimise this code because the number of actual tags is going to be so low that it won't be worth the extra complication in the code. 

As for inconsistencies, I wouldn't worry about those right now. This is just the template that we're working on and there will likely be some updates that will need to happen before we release it on the actual blog anyway. Will might tweak the title of some of the tags for example. As long as our template takes the `More <tag name>...` from the **data** in the tag model then that is the way that we should proceed 👍 

btw your implementation for how to select the different types of tags and then the remaining "subject tags" is **exactly** how I was imagining it 😍

**Comment by alexeykostevich** [comment]
Sounds great! Thank you, @mansona , for your kind words, guidance and super detailed answers!

I've opened a PR with the implemented `TagPanel` component. You could have a look at the component if you wish while I'm working on integration testing.
