### ISSUE TITLE
Implement Post Page

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#32]
## Description

Implement the main "post" page. If you click on one of the articles in the index page you will be directed to the post page that shows the full content of a post.

Note: this page does not have a defined design for it. You should be able to implement it using the styleguide documentation (see link below). If you feel like you need some guidance please feel free to ask us in the comments on this issue, or by reaching out to us on the #st-website channel on Discord. 

If you would like to work on this issue you can "claim" it by commenting and letting us know that you would like to work on it 👍 

## Supporting information - please read if you are new to this project

This redesign effort is powered by the new version of the Ember Styleguide. You should be able to implement everything you need for this feature by following the [new documentation for the ember-styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/) but if you think there is not enough documentation please let us know and we will point you in the right direction.

In most cases you should not need any CSS to implement this issue for the blog template, you should instead be trying to make use of the helpers and components that are documented in the ember-styleguide. This is not a strict rule, there may be cases where the documentation in the ember-styleguide is lacking or some custom CSS is actually needed. If you have any questions please comment on this issue or reach out to us on the `#st-website` channel on the [Ember Community Discord](https://discord.gg/emberjs)

**Comment by ankushdharkar** [comment]
I would like to work on this please :)
@mansona
