### ISSUE TITLE
Make sure that TagPostList component always shows the most recent 3 posts in each tag

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#36]
You can see the start of this discussion in this issue: https://github.com/ember-learn/empress-blog-ember-template/issues/26 but essentially the problem is that currently `@tag.posts` is not an array that is in the order of most recent to oldest.

This would ideally be something that we should fix on the "model-level" so that template authors shouldn't need to worry about it, but if that is proving too difficult before release we could always fall back to adding some logic to TagPostList that deals with this 👍 

Just to be clear: the preferred solution to this is solving it on a model-level upstream in empress-blog

**Comment by Mikek2252** [comment]
Hey @mansona, im happy to help with this, but im not 100% sure what you mean by model level, because i can't see any model in empress-blog

**Comment by Mikek2252** [comment]
Oh i found the model now, my bad

**Comment by Mikek2252** [comment]
Just so we are on the same page, i assume i am adding a computed property that filters the posts, based on date, then updating the tagPostList to use the new computed property.
