### ISSUE TITLE
Accessibility related sidebar refinements

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#43]
This is a follow on issue to #23 that aims to list of of the things necessary to get the sidebar ready for release 👍 

- [x] Make sure everything is accessible on mobile (on desktop this component does nothing, it is just a nav)
- [ ] ~~Implement proper design for the header of the overlay~~ moved to https://github.com/ember-learn/empress-blog-ember-template/issues/47
- [ ] ~~decide on a closing animation~~ moved to https://github.com/ember-learn/empress-blog-ember-template/issues/47

**Comment by nickschot** [comment]
As I can't edit the above here's a list of accessibility points:

- [ ] move focus to the `<nav>` container when it is opened (preferably without tab index)
- [ ] add `aria-expanded` to the nav
- [ ] remove `title` from toggle sidebar/close button
- [ ] add aria-hidden=true to the SVGs
- [ ] remove `role=complementary` from nav element

**Comment by nickschot** [comment]
Focus already seems to automatically be on the sidebar when opened (first tab selects top most focusable item in the sidebar). Is this good enough? Do we want actual focus trapping? Implementing that is slightly more involved as it has to be disabled for non-mobile.

**Comment by nickschot** [comment]
We'll have to add the "Primary site navigation" aria-label in styleguide itself.
