### ISSUE TITLE
remove the indent on the tag-panel component

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#49]
In the `<TagPanel />` component the listed posts are currently indented form the title of the tag section. Apparently this was a bit of a bug with the design file and they were never intended to be indented.

The design should look more like this: https://app.abstract.com/share/a0507989-278d-4684-9c1c-c436eddbba2b?collectionId=3dd6309b-7cfa-4735-85b2-3b10305b19ae&collectionLayerId=494a5919-3bdc-437f-8971-8a947fe05e81&present=true&preview=false&sha=9fae4344280180d331d3c43c1738b89881fa0b63

where you can see that the title of the tag section and the posts in that section are flush with each other

**Comment by Mikek2252** [comment]
Hey, is it alright if i pick this up?

**Comment by Mikek2252** [comment]
@mansona I guess this would also need to be updated in `TagPostList`?
