### ISSUE TITLE
Pagination needs to work

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#5]
As there are so many existing blogs on the Ember blog we **need** pagination to be working for this project!

Currently ember-ghost doesn't support pagination but it is something that we would like to have 👍 

The main place where we would need pagination is the creation of a "collection" in the broccoli code https://github.com/empress/ember-ghost/blob/master/index.js#L76 it is creating a single "collection" from all the content (posts) using the functionality of broccoli-static-site-json https://github.com/stonecircle/broccoli-static-site-json#collections

We need to extend the implementation of collections so that it produces multiple "pages" of collections and then fix the ember-ghost implementation so that it makes use of these pages correctly 👍

**Comment by amyrlam** [comment]
Make this change on https://github.com/empress/ember-ghost

```
if model.hasNext
  click here
```

**Comment by mansona** [comment]
empress-blog (formally ember-ghost) now supports pagination
