### ISSUE TITLE
Implement the Author page design

### ISSUE THREAD

**Issue by mansona** [ember-learn/empress-blog-ember-template#68]
## Description

Implement the Author page design. This is mostly there but the author name and details need to be moved slightly to match the design in Abstract

<img width="454" alt="Screenshot 2020-07-28 at 21 31 45" src="https://user-images.githubusercontent.com/594890/88718390-ceac3000-d119-11ea-93e3-022f648b28bb.png">

Abstract link: https://share.goabstract.com/a0507989-278d-4684-9c1c-c436eddbba2b?collectionLayerId=494a5919-3bdc-437f-8971-8a947fe05e81&mode=design

Here is an example of what it looks like currently: https://deploy-preview-7--ember-blog-legacy.netlify.app/author/matthew-beale

If you would like to work on this issue you can "claim" it by commenting and letting us know that you would like to work on it 👍 

**Notes: **

- the pagination on this page has a "read more" button which does not match the Abstract. This is expected and is not part of this issue
- There is a different issue to properly style the `<hr>` tags https://github.com/ember-learn/ember-styleguide/issues/329
- you should make sure that the tag sidebar that is available on other pages shows up on the author page (I think there is some code that is telling it to hide itself which can be removed)

## Supporting information - please read if you are new to this project

This redesign effort is powered by the new version of the Ember Styleguide. You should be able to implement everything you need for this feature by following the [new documentation for the ember-styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/) but if you think there is not enough documentation please let us know and we will point you in the right direction.

In most cases you should not need any CSS to implement this issue for the blog template, you should instead be trying to make use of the helpers and components that are documented in the ember-styleguide. This is not a strict rule, there may be cases where the documentation in the ember-styleguide is lacking or some custom CSS is actually needed. If you have any questions please comment on this issue or reach out to us on the `#st-website` channel on the [Ember Community Discord](https://discord.gg/emberjs)

**Comment by claeusdev** [comment]
@mansona i would like to work on this.

**Comment by mansona** [comment]
This work was merged 🎉  thanks @claeusdev and @nickschot for the help on this one 🎉
